#!/usr/bin/python

import csv
import os
import sys

if __name__ == '__main__':
    cur_file = os.path.abspath(__file__)
    django_dir = os.path.abspath(os.path.join(os.path.dirname(cur_file), '..'))
    sys.path.append(django_dir)
    os.environ['DJANGO_SETTINGS_MODULE'] = 'settings'

from django.db.models import Q
from django.utils import html

import groups.models


Qsa = Q(group_status__slug__in=('active', 'suspended', ))
functions = {
    'finboard' : {
        'format' : "%(name)s;%(officer_email)s",
        'predicate' : Qsa & Q(group_funding__slug='undergrad', group_class__slug='mit-funded', ),
    },
    'nolist' : {
        'format' : "%(name)s <%(officer_email)s>",
        'predicate' : Qsa & Q(officer_email=""),
    },
    'asa-official' : {
        'format' : '"%(name)s" <%(officer_email)s>',
        'predicate' : Q(group_status__slug='active'),
    },
    'emails-only' : {
        'format' : '%(officer_email)s',
        'predicate' : Qsa,
    },
    'midway' : {
        'prefix': """
        <!-- Automatically generated by %(script)s %(mode)s.
        Do not edit; instead re-run that script (or edit it as necessary). -->
        """,
        'format' : '<option value="%(html_name)s">%(html_name)s</option>',
        'predicate' : Q(group_status__slug__in=['active', 'suspended', 'applying', 'nge'], group_class__gets_publicity=True, ),
    },
}

def do_output(mode):
    spec = functions[mode]
    format = spec['format']
    predicate = spec['predicate']
    gs = groups.models.Group.objects.filter(predicate)
    static_args = {'script': 'groups/format_groups.py', 'mode':mode, }
    if 'prefix' in spec:
        print spec['prefix'] % static_args
    for group in gs:
        print format % {
            'name':group.name,
            'html_name':html.escape(group.name),
            'officer_email':group.officer_email,
        }
    if 'suffix' in spec:
        print spec['suffix'] % static_args

if __name__ == "__main__":
    do_output(sys.argv[1])
